#-------------------------------------------------------------------------------
# Author      : Ethan Rietz
# Date        : 2021-07-28
# Description : Main Alacritty config file
#     The default config file (which is highly commented) can be found at
#     /usr/share/doc/alacritty/example/alacritty.yml
#-------------------------------------------------------------------------------

env:
  # this must be xterm-256color for vim to get termguicolors inside tmux
  TERM: xterm-256color  # defaults to `alacritty`

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 5000   # defaults to 10000

font:
  normal:
    # family: IBM Plex Mono
    # family: Ubuntu Mono
    family: JetBrains Mono
  size: 15

# TODO: Move these keybindings to a new alacritty.yml for windows and load
# this file using an include section
# key_bindings:
  # For using ctrl-6 in vim to switch to last file
  # - { key: Key6,     mods: Control, chars:  "\x1e"         }
  # Previous tmux prefix key which can probably be deleted
  # - { key: Space,    mods: Control, chars:  "\x00"         }

# Colors
draw_bold_text_with_bright_colors: true

schemes:
  solarized_light: &solarized_light
    primary:
      background: '#fdf6e3' # base3
      foreground: '#657b83' # base00

    # Cursor colors
    cursor:
      text:   '#fdf6e3' # base3
      cursor: '#657b83' # base00

    # Normal colors
    normal:
      black:   '#073642' # base02
      red:     '#dc322f' # red
      green:   '#859900' # green
      yellow:  '#b58900' # yellow
      blue:    '#268bd2' # blue
      magenta: '#d33682' # magenta
      cyan:    '#2aa198' # cyan
      white:   '#eee8d5' # base2

    # Bright colors
    bright:
      black:   '#002b36' # base03
      red:     '#cb4b16' # orange
      green:   '#586e75' # base01
      yellow:  '#657b83' # base00
      blue:    '#839496' # base0
      magenta: '#6c71c4' # violet
      cyan:    '#93a1a1' # base1
      white:   '#fdf6e3' # base3

  gruvbox_light: &gruvbox_light
    primary:
      background: '#fbf1c7'
      foreground: '#3c3836'
    cursor:
      cursor: '#282828'
      text: '#fbf1c7'
    normal:
      black:   '#fbf1c7'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#7c6f64'

    bright:
      black:   '#928374'
      red:     '#9d0006'
      green:   '#79740e'
      yellow:  '#b57614'
      blue:    '#076678'
      magenta: '#8f3f71'
      cyan:    '#427b58'
      white:   '#3c3836'
  gruvbox_dark: &gruvbox_dark
    primary: 
      background: '#282828'
      foreground: '#ebdbb2'
    cursor:
      cursor: '#fbf1c7'
      text: '#282828'

    normal:
      black:   '#282828'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#a89984'

    bright:
      black:   '#928374'
      red:     '#fb4934'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#ebdbb2'

  voodoo: &voodoo
    primary: 
      background: '#333333'
      foreground: '#ededed'
    cursor:
      cursor: '#fbf1c7'
      text: '#282828'

    normal:
      black:   '#333333'
      red:     '#fc8d62'
      green:   '#a6d854'
      yellow:  '#ffd92f'
      blue:    '#8da0cb'
      magenta: '#e78ac3'
      cyan:    '#66c2a5'
      white:   '#ededed'
    bright:
      black:   '#928374'
      red:     '#fb8072'
      green:   '#b3de69'
      yellow:  '#ffffb3'
      blue:    '#80b1d3'
      magenta: '#bebada'
      cyan:    '#8dd3c7'
      white:   '#ededed'

colors: *gruvbox_dark
