-- vim.g.coq_settings = {
--     ["auto_start"] = true,
--     ["keymap"] = {
--         ["jump_to_mark"] = "<c-l>",     -- next snippet placeholder (c-h seems backwards)
--         ["manual_complete"] = "<c-h>"   -- show help (default interfered with tmux prefix)
--     }
-- }

-- TODO: setup completion settings per lsp
-- local lsp = require "lspconfig"
-- local coq = require "coq" -- add this
-- lsp.<server>.setup(<stuff...>)                              -- before
-- lsp.<server>.setup(coq.lsp_ensure_capabilities(<stuff...>)) -- after
--
