filetype plugin indent on
syntax enable
set relativenumber
set ignorecase
set smartcase
set spellfile=~/.vim/spell/en.utf-8.add
set wildmenu
set wildmode=longest:full,full
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set mouse=a
set nowrap
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch
set termguicolors
set scrolloff=8
set colorcolumn=80
set updatetime=50
set backspace=indent,eol,start
highlight ColorColumn ctermbg=0 guibg=lightgrey

au BufNewFile,BufFilePre,BufRead *.md set filetype=markdown
au BufNewFile,BufFilePre,BufRead *.snippets set filetype=snippets
au BufNewFile,BufFilePre,BufRead *.zsh,*.slurm,*.torque,*.pbs set filetype=zsh

source ~/.vim/rc_files/plugins.vim
source ~/.vim/rc_files/mappings.vim
source ~/.vim/rc_files/functions.vim