#!/usr/bin/env node
'use strict';

const child_process = require('child_process');
const process = require('process');

function main() {
    const branches = getBranches();
    const userChoice = selectBranch(branches);
    checkoutBranch(userChoice);
}

function dieOnFail(childProcess) {
    if (childProcess.status != 0) {
        console.log(childProcess.stdout.toString());
        console.error(childProcess.stderr.toString());
        process.exit(1);
    }
}

function getBranches() {
    const cp =  child_process.spawnSync("git", ["branch", "-r"]);
    dieOnFail(cp);
    return cp.stdout.toString();
}

// - fzf cleverly reads from /dev/tty instead of from stdin
// - fzf's tui is printed to stderr
// - the result of fzf's selection is printed to stdout
function selectBranch(branches) {
    const cp = child_process.spawnSync(
        "fzf",
        {
            input: branches,    // specifying input overrides stdio[0]
            stdio: ['pipe', 'pipe', 'inherit'] // [stdin, stdout, stderr]
        }
    )
    dieOnFail(cp);
    return cp.stdout.toString().trim();
}

function checkoutBranch(remoteBranch) {
    const localBranch = remoteBranch.split("origin/")[1];
    const cp = child_process.spawnSync(
        "git",
        ["checkout", "-b", localBranch, remoteBranch]
    );
    dieOnFail(cp);
}

main();
