#!/bin/sh
# Author      : Ethan Rietz
# Date        : 2021-09-11
# Description : DWM Status Bar

print_memory(){
    awk '/MemAvailable/ { printf "%.0f GB", $2/1024 }' /proc/meminfo
}

print_tempurature(){
    [ -f /sys/class/thermal/thermal_zone0/temp ] || return 0
    echo "$(head -c 2 /sys/class/thermal/thermal_zone0/temp)C"
}

print_battery(){
    awk '{ sum += $1 } END { print sum "% charge"}' /sys/class/power_supply/BAT*/capacity
}

print_date(){
    date "+%a %m-%d %T"
}

while true
do
    xsetroot -name " $(print_memory) | $(print_tempurature) | $(print_battery) | $(print_date)"
    sleep 1
done
