name: Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  install_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Python format check
        run: black --check .

      - name: Install stylua
        run: cargo install stylua

      - name: Lua format check
        run: stylua -a --check .

      - name: Install shfmt
        run: go install mvdan.cc/sh/v3/cmd/shfmt@latest

      - name: Shell format check
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          for file in $(shfmt -l . 2>&1 | awk -F ':' '{print $1}' | grep -v '\.zsh$'); do
            shfmt -l "$file"
          done
