name: Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  install_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: jdx/mise-action@v2
        with:
          version: latest
          install: true
          cache: true
          log_level: debug

      - name: Lua format check
        run: mise run "lint:*"
