name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  install_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install black
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
        run: pip install black

      - name: Python format check
        run: black --check .

      - name: Install stylua
        run: sudo apt install -y stylua

      - name: Lua format check
        run: stylua -a --check .
